// This class is auto-generated by ConstantClassesGenerator. Do not modify
public static class KResources
{
	public const string BUSH_SMALL = "Prefabs/BushSmall";
	public const string CAMERA_BLACK_BARS = "Prefabs/CameraBlackBars";
	public const string CAMERA_IN_FRONT = "Prefabs/CameraInFront";
	public const string CASTLE_SIMPLE = "Prefabs/CastleSimple";
	public const string CLOUD_SMALL = "Prefabs/CloudSmall";
	public const string FALL = "Prefabs/Fall";
	public const string FLOOR_BRICK10X2 = "Prefabs/FloorBrick10x2";
	public const string FLOOR_BRICK20X2 = "Prefabs/FloorBrick20x2";
	public const string FLOOR_BRICK2X2 = "Prefabs/FloorBrick2x2";
	public const string FLOOR_BRICK2X6 = "Prefabs/FloorBrick2x6";
	public const string FLOOR_BRICK30X2 = "Prefabs/FloorBrick30x2";
	public const string FPS = "Prefabs/FPS";
	public const string GHOST = "Prefabs/Ghost";
	public const string GOAL = "Prefabs/Goal";
	public const string GOOMBA = "Prefabs/Goomba";
	public const string GUI_GAMEPAD = "Prefabs/GUI_Gamepad";
	public const string GUI_OPTION = "Prefabs/GUI_Option";
	public const string GUI_QUIT = "Prefabs/GUI_Quit";
	public const string GUI_SPLASH_IMAGE = "Prefabs/GUI_SplashImage";
	public const string IMMERSIVE_MODE_ENABLER = "Prefabs/ImmersiveModeEnabler";
	public const string KOOPA_TROOPA = "Prefabs/KoopaTroopa";
	public const string MAIN_CAMERA = "Prefabs/MainCamera";
	public const string MARIO = "Prefabs/Mario";
	public const string ONE_WAY_GRASS_PLATFORMER = "Prefabs/OneWayGrassPlatformer";
	public const string PAUSE_GAME_UNITY_LISTENER = "Prefabs/PauseGameUnityListener";
	public const string SPAWN_POSITION = "Prefabs/SpawnPosition";
	public const string START_LEVEL = "Prefabs/StartLevel";
	public const string TOUCH_EVENT_UNITY_UPDATER = "Prefabs/TouchEventUnityUpdater";
}