// This class is auto-generated by ConstantClassesGenerator. Do not modify
public enum KScenes
{
	init = 0,
	SplashScreen = 1,
	LevelSelection = 2,
	Level_01 = 3,
	Level_02 = 4,
	Level_03 = 5,
	Level_04 = 6

}