// This class is auto-generated by ConstantClassesGenerator. Do not modify
public static class KTags
{
	public const string UNTAGGED = "Untagged";
	public const string RESPAWN = "Respawn";
	public const string FINISH = "Finish";
	public const string EDITOR_ONLY = "EditorOnly";
	public const string MAIN_CAMERA = "MainCamera";
	public const string PLAYER = "Player";
	public const string GAME_CONTROLLER = "GameController";
}